apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: system-uat
  labels:
   app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx			
  template:
    metadata:
      labels:
        app: nginx	
    spec:
      containers:
      - name: nginx
        image: docker.registry.local:5000/nginx:v1.${BUILD_NUMBER}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: system-uat
spec:
  type: NodePort
  ports:
    - targetPort: 8081
      port: 8081
      nodePort: 30009
  selector:
    app: nginx
