---
# tasks file for haproxy
   - name: Install EPEL Release         
     package:         
        name: epel-release         
        state: present

   - name: Install Nginx 
     package: 
        name: nginx         
        state: present

   - name: Start Nginx server         
     systemd:        
        name: nginx         
        enabled: yes         
        state: started

   - name: Wait for server to start         
     wait_for:         
        port: 80  

