---
# tasks file for haproxy
   - name: Install EPEL Release         
     package:         
        name: epel-release         
        state: present

   - name: Install Nginx 
     package: 
        name: nginx         
        state: present

   - firewalld:
        port: 80/tcp
        permanent: true         
        state: enabled
